### ISSUE TITLE
/api/block?index=NaN crashes server

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/messages-from-the-mines#19]
```
[mysql] (0.09 sec) SELECT DISTINCT SQL_CACHE block_height FROM op_return_address_messages_unique WHERE valid = 1 AND `data` LIKE CONCAT('%', HEX('hitler'), '%') ORDER BY block_height;
[http]  GET /api/block?index=NaN
[error] error getting block
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Connection.js:208:25)
    at Object.getBlock (/home/ubuntu/messages-from-the-mines/mftm-backend/src/utils.js:76:13)
    at dbPool.getConnection (/home/ubuntu/messages-from-the-mines/mftm-backend/server.js:141:11)
    at Ping.onOperationComplete [as _callback] (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'NaN\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT block_height, block_hash, block_timestamp FROM coinbase_messages WHERE block_height = NaN;' }
[error] error getting block
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Connection.js:208:25)
    at Object.getBlock (/home/ubuntu/messages-from-the-mines/mftm-backend/src/utils.js:80:13)
    at dbPool.getConnection (/home/ubuntu/messages-from-the-mines/mftm-backend/server.js:141:11)
    at Ping.onOperationComplete [as _callback] (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.Sequence.end (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Ping.Sequence.OkPacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'NaN\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT block_height, block_hash, block_timestamp FROM address_messages WHERE block_height = NaN;' }
/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/express/lib/response.js:767:10)
    at ServerResponse.contentType (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/express/lib/response.js:595:15)
    at ServerResponse.sendStatus (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/express/lib/response.js:357:8)
    at utils.getBlock (/home/ubuntu/messages-from-the-mines/mftm-backend/server.js:145:11)
    at cb (/home/ubuntu/messages-from-the-mines/mftm-backend/src/utils.js:89:4)
    at Query.connection.query [as _callback] (/home/ubuntu/messages-from-the-mines/mftm-backend/src/utils.js:80:39)
    at Query.Sequence.end (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/ubuntu/messages-from-the-mines/mftm-backend/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
```

**Comment by brannondorsey** [comment]
Fixed.
